// flow-typed signature: 7338a2afc24702805051c33b938ac0f3
// flow-typed version: <<STUB>>/flow-watch_v^1.1.4/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'flow-watch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'flow-watch' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'flow-watch/src/flow-watch' {
  declare module.exports: any
}

declare module 'flow-watch/src/runFlow' {
  declare module.exports: any
}

// Filename aliases
declare module 'flow-watch/src/flow-watch.js' {
  declare module.exports: $Exports<'flow-watch/src/flow-watch'>
}
declare module 'flow-watch/src/runFlow.js' {
  declare module.exports: $Exports<'flow-watch/src/runFlow'>
}
