// flow-typed signature: cac7ca7b6507916c8be93c9a174dc0fe
// flow-typed version: <<STUB>>/get-node-dimensions_v^1.2.0/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'get-node-dimensions'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'get-node-dimensions' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'get-node-dimensions/dist/get-node-dimensions' {
  declare module.exports: any
}

declare module 'get-node-dimensions/dist/get-node-dimensions.min' {
  declare module.exports: any
}

declare module 'get-node-dimensions/lib/get-clone-dimensions' {
  declare module.exports: any
}

declare module 'get-node-dimensions/lib/get-margin' {
  declare module.exports: any
}

declare module 'get-node-dimensions/lib/get-node-dimensions' {
  declare module.exports: any
}

// Filename aliases
declare module 'get-node-dimensions/dist/get-node-dimensions.js' {
  declare module.exports: $Exports<
    'get-node-dimensions/dist/get-node-dimensions'
  >
}
declare module 'get-node-dimensions/dist/get-node-dimensions.min.js' {
  declare module.exports: $Exports<
    'get-node-dimensions/dist/get-node-dimensions.min'
  >
}
declare module 'get-node-dimensions/lib/get-clone-dimensions.js' {
  declare module.exports: $Exports<
    'get-node-dimensions/lib/get-clone-dimensions'
  >
}
declare module 'get-node-dimensions/lib/get-margin.js' {
  declare module.exports: $Exports<'get-node-dimensions/lib/get-margin'>
}
declare module 'get-node-dimensions/lib/get-node-dimensions.js' {
  declare module.exports: $Exports<
    'get-node-dimensions/lib/get-node-dimensions'
  >
}
